module.exports = {
  '--border': '#5d4d7a',
  '--text': '#b2b2b2',
  '--text-color': '#b2b2b2',
  '--dim-text': '#686868',
  '--background': '#292b2e',
  '--general-background-color': '#292b2e',
  '--general-background': '#292b2e',
  '--code-background-color': '#100a14',
  '--link-color': '#2d9574',
  '--visited-link-color': '#4f97d7',
  '--visited-link-background-color': '#44505c',
  '--heading-background-color': '#292b2e',
  '--head1-color': '#4f97d7',
  '--head1-background-color': '#293239',
  '--highlight-color': '#e3dedd',
  '--highlight-background-color': '#3b314d',
  '--tab-inactive-color': '#2aa1ae',
  '--tab-inactive-background-color': '#292b2e',
  '--tab-left-inactive-border-radius': '0 0 0.5em 0',
  '--tab-right-inactive-border-radius': '0 0 0 0.5em',
  // Setting the container's background-color makes it so we get the S shaped
  // border radius on the tabs, because the border-radius on the bottom allows
  // the background-color of the container to leak through.
  '--tab-inactive-sibling-container-background-color': '#5d4d7a',
  '--tab-active-background-color': '#5d4d7a',
  '--tab-active-border-radius': '0.5em 0.5em 0 0',
  '--tab-active-color': '#b2b2b2',
  '--tab-list-background-color': '#292b2e',
  '--button-background': '#2aa1ae',
  '--button-background-color': '#2aa1ae',
  '--button-color': '#292e34',
  '--input-color': '#2aa1ae',
  '--input-background-color': '#292e34',
  '--thin-border': '0.1em solid #5d4d7a',
  '--thin-border-color': '#5d4d7a',
  '--diff-add-color': '#293235',
  '--diff-add-background-color': '#86dc2f',
  '--diff-minor-add-background-color': '#67b11d',
  '--diff-remove-color': '#3c2a2c',
  '--diff-remove-background-color': '#e0616d',
  '--diff-minor-remove-background-color': '#ce537a',
  '--open-ticket-color': '#86dc2f',
  '--closed-ticket-color': '#ce537a',
}
