################################################################################
# SSH configuration for Gitea access using an agenix-managed development key.
#
# This is for headless hosts that have their own SSH keypair (generated by
# agenix-rekey) rather than relying on agent-forwarded keys from a workstation.
################################################################################
{ facts, ... }:
{
  programs.ssh = {
    matchBlocks = {
      "gitea.${facts.network.domain}" = {
        port = 2222;
        user = "git";
        identityFile = "/run/agenix/logan-dev-ssh";
        identitiesOnly = true;
      };
    };
  };
}
