################################################################################
# Give us a default disk for Rasbperry Pi SD cards.
#
# This may not work for all Raspberry Pi images going forward.  You can see what
# partitions are availble (via their /dev file) and the partition type with
# `lsblk`.
#
# This partition table was generated by _something_ but I'm not sure what.  Much
# documentation suggests zfs is to be used, but whatever built me a working
# image didn't include that.
################################################################################
{ ... }: {
  boot.loader.grub.enable = false;
  boot.initrd.supportedFilesystems = [ "zfs" "vfat" "ext4" ];
  boot.supportedFilesystems = [ "zfs" "vfat" "ext4" ];
  # This isn't actually /boot or /-anything really.
  # fileSystems."/boot" = {
  #   device = "/dev/mmcblk0p1";
  #   fsType = "vfat";
  # };
  fileSystems."/" = {
    device = "/dev/mmcblk0p2";
    fsType = "vfat";
  };
}
