#!/usr/bin/env bash
################################################################################
# `grep` doesn't work well with `set -o pipefail` because it returns exit code 1
# if there are no matches.  We don't care about that, so make sure we zero-ize a
# 1.  Other errors (2+) are real errors we should pay attention to though.
################################################################################
set -euo pipefail

grep "$@" || test $? = 1;
