################################################################################
# Stalwart mail server configuration for silicon.
#
# Two mail domains:
#   proton        Internal LAN-only; no external MX.
#   meshward.com  Business domain; external MX, DKIM-signed.
#
# Authentication is LDAP-backed against OpenLDAP on silicon.  The stalwart
# service account is declared here; ldap-auth.nix auto-emits its password
# secrets.
#
# Before first deploy, generate all secrets:
#   agenix rekey generate --rekey -a
# Then commit the generated secrets/tls-mail.proton.crt to the repository.
#
# After the DKIM secret is generated, extract the public key for the DNS TXT
# record at default._domainkey.meshward.com:
#   openssl pkey -in <(rage --decrypt secrets/generated/stalwart-dkim-meshward.age) \
#     -pubout | grep -v '^-----' | tr -d '\n'
################################################################################
{ facts, ... }:
let
  domain = facts.network.domain;
  baseDn = "dc=${domain},dc=org";
in
{
  # Register the stalwart LDAP service account.  ldap-auth.nix auto-emits:
  #   stalwart-ldap-password         — plaintext, delivered via LoadCredential
  #   stalwart-ldap-password-hashed  — argon2 hash for the LDAP reconciler
  auth.ldap.users.stalwart = {
    email = "stalwart@${domain}";
    fullName = "Stalwart mail service account";
    type = "service";
    group = "stalwart-mail";
    managed = true;
  };

  # Ed25519 DKIM private key for meshward.com.  rekeyFile is omitted so
  # agenix-rekey places it in secrets/generated/ automatically.
  age.secrets.stalwart-dkim-meshward = {
    generator.script = "stalwart-dkim-key";
  };

  services.stalwart-host = {
    enable = true;

    internalDomain = domain;

    externalDomains = [
      {
        domain = "meshward.com";
        dkimSelector = "default";
        dkimSecretName = "stalwart-dkim-meshward";
        catchAll = false;
      }
    ];

    # TODO: Wire into Stalwart settings once the LDAP schema includes
    # mailAlias, or once a Stalwart-native alias mechanism is confirmed.
    aliases = {
      "logan@meshward.com" = "logustus@${domain}";
    };

    ldap = {
      url = "ldaps://ldap.${domain}:636";
      baseDn = baseDn;
    };

    relayNetworks = [
      "${facts.network.subnets.barnett-main}.0/24"
    ];

    internalTls = {
      # Generated by agenix-rekey via tls.tls-leafs in the module.  The .crt
      # is a plain file committed to the repo after running agenix rekey.
      certFile = "${../secrets/tls-mail.proton.crt}";
      keySecretName = "tls-mail.proton.key";
    };
  };

  # Let's Encrypt certificate for mail.meshward.com via DNS challenge.
  # DNS challenge is preferred over HTTP because it does not require port 80
  # to be reachable from the internet.
  #
  # TODO: Set dnsProvider and credentialsFile once the Porkbun API key secret
  # is created.  The credentials file should contain:
  #   PORKBUN_API_KEY=pk1_...
  #   PORKBUN_SECRET_API_KEY=sk1_...
  # security.acme = {
  #   acceptTerms = true;
  #   defaults.email = "admin@meshward.com";
  #   certs."mail.meshward.com" = {
  #     # dnsProvider = "porkbun";
  #     # credentialsFile = config.age.secrets.porkbun-api-keys.path;
  #     # Reload Stalwart after certificate renewal so the new cert is used.
  #     postRun = "systemctl reload-or-restart stalwart-mail.service || true";
  #   };
  # };
}
